### ISSUE TITLE
After Fabric and Fabric Api update server crashes, MC 1.20.1

### ISSUE THREAD

**Issue by Pokihead** [iChun/Death-Counter#12]
After updating to Fabric 0.15.11 and updating Fabric Api to 0.92.2 (All MC 1.20.1) Death Counter crashes the server on boot up.
On client it still works.
Could be a problem from completeconfig to don't know.

[latest.log](https://github.com/user-attachments/files/15657721/latest.log)

**Comment by iChun** [comment]
Ah this was fixed by the port to iChunUtil in place of CompleteConfig.
