### ISSUE TITLE
Death Counter on player death

### ISSUE THREAD

**Issue by Yourname942** [iChun/Death-Counter#6]
Please add a config to have the message appear when a player dies (instead of manually typing /dc)
Additional config options for this:
- optional to make it local
- optional to make it global

Minecraft 1.15.2
Forge 31.2.36

**Comment by iChun** [comment]
Isn't there already one? What version are you using?

**Comment by Yourname942** [comment]
There is a config, but I do not see the option:
1) for the death counter to appear automatically when a player dies
2) an in game option for player to show/hide the messages (ie. other players can see them, but if player A wants to see it, but player B does not, this would allow them the freedom to do so) 

**Note:** 
I don't know if there is an option already in game for players to enable/disable seeing the death counter messages

I'm using Death Counter 1.2.0


```
#General settings
[general]
	#What kind of message should we send players when they die?
	#Allowed Values: NONE, SHORT, LONG
	messageType = "LONG"
	#Do not persist deaths across sessions? Turning this on disables saving deaths to server folder.
	singleSession = false
	#Number of names to show in the leaderboard
	#Range: 1 ~ 50
	leaderboardCount = 5
	#Permission level required to use the op commands for Death Counter
	#Range: 0 ~ 4
	commandPermissionLevel = 1
```
