### ISSUE TITLE
Not Working on Server

### ISSUE THREAD

**Issue by CGV224** [iChun/Death-Counter#8]
I am running a server using Apex Hosting and whenever I use the commands in the server it doesn't work. But, when I try it out in single player it does work. How do I get this mod to work in the server?

**Comment by iChun** [comment]
Have you installed the mod on the server? If you plan to use it on a multiplayer server then installing it on just your client isn't sufficient.

**Comment by CGV224** [comment]
Yeah I'm pretty sure that it was installed on the server but I'll go check again
