### ISSUE TITLE
Deathcounter 1.19-1.2.1 Crashing 1.19.1 Server

### ISSUE THREAD

**Issue by Pokihead** [iChun/Death-Counter#9]
Like title says.
Deathcounter 1.19-1.2.1 doesn't work anymore in MC 1.19.1 with Forge 42.0.0
Server crashes after a few minutes working.
Crashlog:
https://pastebin.com/kaxL285n

**Comment by iChun** [comment]
Already addressed and update release on CurseForge a couple months ago. Closing
